# Generated by Django 3.1.2 on 2021-08-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210814_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='alias',
            field=models.TextField(default='TBD', unique=True, verbose_name='Псевдоним'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telescope',
            name='altitude',
            field=models.FloatField(default=0, verbose_name='Высота над уровнем моря в м'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telescope',
            name='code',
            field=models.IntegerField(default=0, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telescope',
            name='fov',
            field=models.FloatField(default=4, verbose_name='Поле зрения в градусах'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telescope',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telescope',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта в градусах'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telescope',
            name='location',
            field=models.TextField(blank=True, default='', verbose_name='Местоположение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telescope',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота в градусах'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telescope',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'В сети'), (0, 'Не в сети')], default=0, verbose_name='Статус'),
        ),
    ]
