# Generated by Django 3.1.2 on 2021-08-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_inputdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Спутник',
                'verbose_name_plural': 'Спутники',
            },
        ),
        migrations.AddField(
            model_name='inputdata',
            name='expected_sat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_inputdata', to='tasks.satellite', verbose_name='Спутник'),
            preserve_default=False,
        ),
    ]
