# Generated by Django 3.1.2 on 2021-08-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20210818_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='expected_sat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_inputdata', to='tasks.satellite', verbose_name='Ожидаемый спутник'),
        ),
    ]
