# Generated by Django 3.1.2 on 2021-08-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_auto_20210818_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdata',
            old_name='dt',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='end_jd',
            field=models.FloatField(null=True, verbose_name='Юлианское время конца наблюдения'),
        ),
        migrations.AddField(
            model_name='task',
            name='input_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tasks.inputdata', verbose_name='Входные данные'),
        ),
        migrations.AddField(
            model_name='task',
            name='jdn',
            field=models.IntegerField(null=True, verbose_name='Юлианская дата начала наблюдения'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_jd',
            field=models.FloatField(null=True, verbose_name='Юлианское время начала наблюдения'),
        ),
        migrations.AddField(
            model_name='telescope',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Создано'), (2, 'Получено телескопом'), (3, 'Выполнено'), (4, 'Не удалось выполнить')], default=1, verbose_name='Статус задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SmallIntegerField(choices=[(1, 'Снимки по точкам'), (2, 'Трэкинг по точкам')], verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tasks.telescope', verbose_name='Телескоп'),
        ),
    ]
