# Generated by Django 3.1.2 on 2021-08-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20210819_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Создано'), (2, 'Получено телескопом'), (3, 'Выполнено'), (4, 'Не удалось выполнить')], default=0, verbose_name='Статус задания'),
        ),
    ]
