# Generated by Django 3.1.2 on 2021-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20210819_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='name',
            field=models.TextField(default='', unique=True, verbose_name='Название спутника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='number',
            field=models.IntegerField(default=0, unique=True, verbose_name='Номер спутника'),
            preserve_default=False,
        ),
    ]
