# Generated by Django 3.1.2 on 2021-08-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20210819_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingdata',
            name='satellite_id',
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_data', to='tasks.satellite', verbose_name='Спутник'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='name',
            field=models.TextField(blank=True, verbose_name='Название спутника'),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='count',
            field=models.IntegerField(default=20, verbose_name='Количество снимков'),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='step_sec',
            field=models.IntegerField(default=1, verbose_name='Шаг по времени'),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_data', to='tasks.task', verbose_name='Задание'),
            preserve_default=False,
        ),
    ]
