# Generated by Django 3.1.2 on 2021-08-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20210819_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='satellite_id',
        ),
        migrations.AddField(
            model_name='point',
            name='jd',
            field=models.FloatField(default=0, verbose_name='Юлианское время снимка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='jdn',
            field=models.IntegerField(default=0, verbose_name='Юлианская дата снимка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='tasks.satellite', verbose_name='Спутник'),
        ),
        migrations.AlterField(
            model_name='point',
            name='beta',
            field=models.FloatField(verbose_name='Угол места'),
        ),
        migrations.AlterField(
            model_name='point',
            name='dt',
            field=models.DateTimeField(verbose_name='Дата и время снимка'),
        ),
        migrations.AlterField(
            model_name='point',
            name='exposure',
            field=models.FloatField(verbose_name='Требуемая выдержка снимка'),
        ),
        migrations.AlterField(
            model_name='point',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='tasks.task', verbose_name='Задание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='step_sec',
            field=models.FloatField(default=1, verbose_name='Шаг по времени'),
        ),
    ]
