# Generated by Django 3.1.2 on 2021-08-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20210819_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='jd',
            field=models.FloatField(default=0, verbose_name='Юлианское время снимка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='jdn',
            field=models.IntegerField(default=0, verbose_name='Юлианская дата снимка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frame',
            name='dt',
            field=models.DateTimeField(verbose_name='Дата и время снимка'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='exposure',
            field=models.FloatField(verbose_name='Требуемая выдержка снимка'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frames', to='tasks.task', verbose_name='Задание'),
            preserve_default=False,
        ),
    ]
