# Generated by Django 3.1.2 on 2021-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20210819_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
