# Generated by Django 3.1.2 on 2021-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20210823_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
