# Generated by Django 3.1.2 on 2021-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_auto_20210823_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='data_type',
            field=models.SmallIntegerField(choices=[(0, 'Нет данных'), (1, 'Элементы орбит в формате TLE'), (2, 'Массив точек в формате JSON')], editable=False, verbose_name='Тип данных'),
        ),
    ]
