# Generated by Django 3.1.2 on 2021-08-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0028_auto_20210824_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_inputdata', to=settings.AUTH_USER_MODEL, verbose_name='Автор входных данных'),
        ),
    ]
