# Generated by Django 3.1.2 on 2021-08-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_auto_20210824_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='expected_sat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_inputdata', to='tasks.satellite', to_field='number', verbose_name='Ожидаемый спутник'),
        ),
        migrations.AlterField(
            model_name='point',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='points', to='tasks.satellite', to_field='number', verbose_name='Спутник'),
        ),
        migrations.AlterField(
            model_name='tledata',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TLE_data', to='tasks.satellite', to_field='number', verbose_name='Спутник'),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_data', to='tasks.satellite', to_field='number', verbose_name='Спутник'),
        ),
    ]
