# Generated by Django 3.1.2 on 2021-08-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_remove_task_input_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='author',
        ),
    ]
