# Generated by Django 3.1.2 on 2021-08-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_remove_inputdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdata',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_inputdata', to='tasks.task', unique=True, verbose_name='Задание'),
        ),
    ]
