# Generated by Django 3.1.2 on 2021-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_auto_20210830_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
