# Generated by Django 3.1.2 on 2021-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_auto_20210830_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='alpha',
            field=models.FloatField(verbose_name='Азимут в градусах'),
        ),
        migrations.AlterField(
            model_name='point',
            name='beta',
            field=models.FloatField(verbose_name='Угол места в градусах'),
        ),
        migrations.AlterField(
            model_name='point',
            name='dt',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='point',
            name='exposure',
            field=models.FloatField(verbose_name='Выдержка снимка в секундах'),
        ),
        migrations.AlterField(
            model_name='point',
            name='jd',
            field=models.FloatField(verbose_name='Юлианское время'),
        ),
        migrations.AlterField(
            model_name='point',
            name='jdn',
            field=models.IntegerField(verbose_name='Юлианская дата'),
        ),
    ]
