# Generated by Django 3.1.2 on 2021-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_auto_20210830_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='cs_type',
            field=models.SmallIntegerField(choices=[(0, 'Земная система координат'), (1, 'Звездная система координат')], default=0, verbose_name='Система координат'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='dt',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='exposure',
            field=models.FloatField(verbose_name='Выдержка снимка в секундах'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frame',
            name='jd',
            field=models.FloatField(verbose_name='Юлианское время'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='jdn',
            field=models.IntegerField(verbose_name='Юлианская дата'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='alpha',
            field=models.FloatField(verbose_name='Азимут в градусах'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='beta',
            field=models.FloatField(verbose_name='Угол места в градусах'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='dt',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='jd',
            field=models.FloatField(verbose_name='Юлианское время'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='jdn',
            field=models.IntegerField(verbose_name='Юлианская дата'),
        ),
    ]
