# Generated by Django 3.1.2 on 2021-08-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_auto_20210831_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='exposure',
            field=models.FloatField(verbose_name='Выдержка снимка в мс'),
        ),
        migrations.AlterField(
            model_name='point',
            name='exposure',
            field=models.FloatField(verbose_name='Выдержка снимка в мс'),
        ),
    ]
