# Generated by Django 3.1.2 on 2021-09-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_auto_20210902_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskresult',
            options={'verbose_name': 'Результат наблюдений', 'verbose_name_plural': 'Результаты наблюдений'},
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='frame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='tasks.frame', verbose_name='Фрейм'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='tasks.point', verbose_name='Точка'),
        ),
    ]
