# Generated by Django 3.1.2 on 2021-09-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_auto_20210902_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackpoint',
            name='task',
        ),
        migrations.DeleteModel(
            name='TrackingData',
        ),
        migrations.DeleteModel(
            name='TrackPoint',
        ),
    ]
