# Generated by Django 3.1.2 on 2021-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_auto_20210907_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='exposure',
        ),
        migrations.RemoveField(
            model_name='point',
            name='mag',
        ),
        migrations.AddField(
            model_name='frame',
            name='mag',
            field=models.FloatField(default=0, verbose_name='Звездная велечина'),
            preserve_default=False,
        ),
    ]
