# Generated by Django 3.1.2 on 2021-09-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_auto_20210907_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='satellite',
        ),
        migrations.AddField(
            model_name='task',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tasks.satellite', to_field='number', verbose_name='Спутник'),
        ),
    ]
