# Generated by Django 3.1.2 on 2021-09-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_auto_20210907_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdata',
            name='expected_sat',
        ),
    ]
